### ISSUE TITLE
Success ve Error yakalama nasıl oluyor?

### ISSUE THREAD

**Issue by e-vural** [abdurrahmanekr/Angularjs-SqlService-Cordova-WebSql-Compatible#5]
Öncelikle emeğiniz için teşekkürler. Yaptığım sorguların success ve ya error oldugunu anlayamıyorum.
Örneğin: Tablo oluşturacağım 

> SQLiteManager.query(query);  

query değişkeni içinde tablo oluşturma kodu var. Tabloyu oluşturuyor sorun yok ancak oluştugunda bir callback nasıl alırım. Ayrıca aynı tablo var olduğu zaman hata almam gerekiyor bunu nasıl yaparım. 

>SQLiteManager.query(query).then(()=>console.log("başarılı")).catch(()=> console.log("hata));

bunu denedim olmadı. yardımcı olur musunuz?

**Comment by abdurrahmanekr** [comment]
Merhaba websqli asenkron çalışabilir bir şekilde tasarlandı. yani sizin çalıştırdığınız insert, update, delete ve query methodları Siz modeli init ederken verdiğiniz timeout değerine göre transaction açar. Yani o değer arasında çalıştırılan methodlar bir transaction kullanır. ör: 
```
SqlService.init({
    ...
    timeout: 5000 // burası 5 saniyede bir transaction açar
})
```
Sadece select sorgusu anlık olarak getirilir. Diğer sorguları da anlık çalıştırmak istiyorsanız. rightNow() kullanmalısınız. ör: 
```
SQLiteManager.rightNow().query(query).then(console.log).catch(console.error);
```
Veya her sorgunun anlık gelmesini istiyorsanız init ederken timeout değerine 0 verirsiniz.

Ayrıca bkz:
http://www.avarekodcu.com/konu/26/websql-ve-sqlitei-verimli-kullanma-kullanimi
https://github.com/abdurrahmanekr/bana-istedigini-sor/issues/68#issuecomment-430663616

**Comment by e-vural** [comment]
Hocam dediğiniz gibi sıfır yapınca veya rightNow() kullanınca success veya error alıyorum.
`SQLiteManager.rightNow().query(query).then(console.log).catch(console.error);`
bu şekilde sorun yok

`SQLiteManager.rightNow().query(query).then((res) => {console.log(res)}).catch((err)=>{console.log(err)});`
Ama bu şekilde dönen objeleri alamıyorum. Bunlar dönmediği için mi yoksa hatalı bir kullanım mı yapıyorum

**Comment by abdurrahmanekr** [comment]
Arrow function bazı tarayıcılar desteklemediği için olabilir. Şöyle deneyin:
```javascript
SQLiteManager.rightNow().query(query)
.then(function (res) {
    console.log(res);
})
.catch(function (err){
    console.log(err);
});
```
