### ISSUE TITLE
Database dosyasını nerede oluşturuyor?

### ISSUE THREAD

**Issue by ilyasbat** [abdurrahmanekr/Angularjs-SqlService-Cordova-WebSql-Compatible#8]
SQLiteManager.init({
id: 'localdb',
dbObject: SQLite,
});

ile veritabanını tanımlıyoruz, okuma yazma işlemi yapabiliyoruz onda da sıkıntı yok ama localdb.db dosyasını bir türlü bulamıyorum. Browser ile oluşturduğum tabloları kontrol etmek istiyorum.

Tüm bilgisayarda *.db araması yaptım ama yok hiçbir şey bulamadım.
React native sürümüm 0.61.5

**Comment by abdurrahmanekr** [comment]
Merhaba react-native diyorsanız, cihazın sql dizinine erişmeyi bilmiyorum. Ama tarayıcıda erişmek için Geliştirici penceresinden > Application > Web SQL kısmından erişebilirsiniz.
