### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [abdurrahmanekr/Angularjs-SqlService-Cordova-WebSql-Compatible#9]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by abdurrahmanekr** [comment]
Hello @codehangen yes it is. I would be glad if you contribute to this project.

**Comment by ghost** [comment]
Hello abdurrahmanekr.

> Hello @codehangen yes it is. I would be glad if you contribute to this project.

thanks for the comment. I want to contribute to this project. So, I will close this issue you answered my doubt.
